name: Main
on:
  push:
    branches:
      - master
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Install dependencies
      run: |
        make clean
        make lint
        make fmt-check
        make misspell-check
        make test-vendor
        make build

