name: Main
on:
  push:
    branches:
      - master
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Install dependencies
        run: |
          make clean
          make fmt-check
          make test-vendor
          make build
          make test
